/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "RCC_interface.h"
#include "DIO_interface.h"

int main(void)

{
	RCC_voidSysClkInt();

	RCC_voidEnablePerClk(APB2, 2);

	DIO_voidSetPinDirection(PORTA, pin1, GPIO_PP_10MHZ);
    /* Loop forever */
	while(1)
	{
		DIO_voidSetPinValue(PORTA, pin1, HIGH);
	}
}
